### PR TITLE
CR-15: Added feature flags to be used in cloud

### PR DESCRIPTION
**Pull request by kyle-marcum**

### CODE REVIEW

**Comment by arthosofteq** [comment]
@romansergeenkosofteq It is not in the scope of this task.

**Review by arthosofteq — APPROVED** [review]
So you decided to keep all flags in the feature-config.json?
Ok. let's go with this approach

**Comment by romansergeenkosofteq** [comment]
> @romansergeenkosofteq It is not in the scope of this task.

then we don't need to put navigation items under feature flag now?

**Comment by arthosofteq** [comment]
@romansergeenkosofteq 
No, we need.
The scope of this particular task was defined and according to it - everything is good.
Disabling entire page using dynamic route needed to be discussed and was descoped.
Except this any other comments?

**Comment by romansergeenkosofteq** [comment]
> @romansergeenkosofteq No, we need. The scope of this particular task was defined and according to it - everything is good. Disabling entire page using dynamic route needed to be discussed and was descoped. Except this any other comments?

thats mean that users will be able to open these pages under feature flag by url or from links in our application. We have a lot of places with links leading to theses pages under feature flag

**Comment by arthosofteq** [comment]
@romansergeenkosofteq correct. it is expected behavior for now

**Review by romansergeenkosofteq — APPROVED** [review]

**Pull request merged**
