### PR TITLE
Removing LGTM

### PR DESCRIPTION
**Pull request by chayim**
The LGTM service is being shut off in two weeks. This pull request aims to remove all references to LGTM. Perhaps LGTM usage should be replaced with codeql, or a repository preferred tool, but IMHO that's the point of a different pull request.

### CODE REVIEW

**Comment by arthosofteq** [comment]
Didn't know that. Make sense. Thanks!

**Review by arthosofteq — APPROVED** [review]

**Comment by arthosofteq** [comment]
@elenaNaboko please, merge when you will be ready

**Review by ankit-gautam23 — APPROVED** [review]
LGTM

**Comment by KIvanow** [comment]
Seems to be outdated (2+ years ago). Reopen if needed with updates.

**Pull request closed without merging**
